CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
	username CITEXT NOT NULL UNIQUE,
	email CITEXT NOT NULL UNIQUE,
	password_hash BYTEA,
	title VARCHAR,
	level SMALLINT NOT NULL DEFAULT 1,
	xp INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);